ResultをDBに保存する
pekorinko/review_check pull request #28
Opened 2021-04-15 12:29 UTC by pekorinko

## やったこと
- ResultをDBに保存する
## やった理由
- ResultをDBに保存することにより、結果画面更新後も更新前に表示されていたResultが表示されて続けるようにしたいため
## 確認項目
-[x] Resultがレコードとして保存される

## Issue
Fix #

2021-04-24 02:16 UTC, mktakuya requested changes
コメントしました！

2021-04-24 02:16 UTC, mktakuya commented on app/controllers/results_controller.rb
> +      @place_id = place.id
Controllerで `@place_id` というように `@` をつけているのを見ると、viewで使うのかな？と思ってしまいます。
実際には使ってなさそうなので、 `@` 外して `place_id` でどうでしょう。

2021-04-24 02:16 UTC, mktakuya commented on test/models/result_test.rb
> +end
たぶんいらないファイルだと思うので、削除しましょう！

2021-04-24 02:16 UTC, mktakuya commented on test/fixtures/results.yml
> +  credible_star_ave: 1.5
これも多分いらないファイルだと思うので削除しましょう！

2021-04-24 02:16 UTC, mktakuya commented on db/migrate/20210419060241_remove_place_name_from_results.rb
> +    remove_column :results, :place_name, :text
これは `Place` で持ってるので、消す感じでOKですね！

2021-04-24 23:13 UTC, pekorinko commented on app/controllers/results_controller.rb
> +      @place_id = place.id
@place_idからplace_idに変更したところ、`lib/my_tools/check_credibility.rb:41`で`ZeroDivisionError (divided by 0):`が出てしまいました。
以下の位置でputs したところ、`puts stars`は何も表示されない、`puts total``puts stars.length`はいずれも「0」と表示されました。

この原因として`lib/my_tools/check_credibility.rb`でReview、Placeそれぞれのplace_idを特定するために
- ８行目で`reviews = Review.where(place_id: @place_id)`
- 35行目で`place = Place.find_by(id: @place_id)`
をしていることから@place_idをplace_idにするとエラーが出てしまうようでした。
この場合、コントローラーでこのまま@place_idのままにするとビューでの使用の誤解を招くため、他の対策案を考えた方が宜しいでしょうか？


【`lib/my_tools/check_credibility.rb`】
```
def credibility
      **reviews = Review.where(place_id: @place_id)**
      selected_reviews =
        reviews.filter_map do |review|
          review if review.text.size >= 50 and review.count >= 20
        end

      texts = reviews.map { |review| review.text }
      stars = reviews.map { |review| review.star }
      **puts '============'
      puts stars
      puts '============'**
      counts = reviews.map { |review| review.count }
      selected_stars =
        selected_reviews.map { |selected_review| selected_review.star }

      total = 0
      count_total = 0
      text_total = 0
      selected_star_total = 0

      texts.each { |text| text_total = text_total + text.size }
      stars.each { |star| total = total + star }
      counts.each { |count| count_total = count_total + count }
      selected_stars.each do |selected_star|
        selected_star_total = selected_star_total + selected_star
      end

      **place = Place.find_by(id: @place_id)
      puts '=========='
      puts total
      puts stars.length
      puts '=========='**
```

2021-04-24 23:17 UTC, pekorinko commented on test/fixtures/results.yml
> +  credible_star_ave: 1.5
`test/fixtures/results.yml`削除しました！現時点で
- `test/fixtures/place_test.rb`
- `test/fixtures/review_test.rb`
も存在しているのですがいずれも消してしまって宜しいでしょうか？

2021-04-24 23:19 UTC, pekorinko commented on test/models/result_test.rb
> +end
`test/models/result_test.rb`削除しました！現時点で
- `test/models/place_test.rb`
- `test/models/review_test.rb`
も存在しているのですがこちらも同じく削除して問題ないでしょうか？

2021-04-24 23:35 UTC, pekorinko commented on db/migrate/20210419060241_remove_place_name_from_results.rb
> +    remove_column :results, :place_name, :text
`20210412084426_create_results.rb`を作った時点ではResultのカラムとして`t.text :place_name`を入れてしまっていたため、これを削除するために`20210419060241_remove_place_name_from_results.rb`にて`remove_column :results, :place_name, :text`を書くことによってResultからplace_nameカラムを削除する処理を書きました。

その上で`rails:db migrate`をやったことでResultからplace_nameが消えたため、`20210419060241_remove_place_name_from_results.rb`の内容は反映済みなことから当ファイルは削除するという認識で合っておりますでしょうか？

今、懸念していることとして、`20210419060241_remove_place_name_from_results.rb`を削除することで`20210412084426_create_results.rb`には`t.text :place_name`が記載されたままなので、またResultがplace_nameカラムを持ってしまうのではないかと考えております。


```
【`20210412084426_create_results.rb`】
class CreateResults < ActiveRecord::Migration[6.1]
  def change
    create_table :results do |t|
      t.text :place_name
      t.text :address
      t.float :star_ave
      t.integer :count_ave
      t.integer :text_ave
      t.float :credible_star_ave

      t.timestamps
    end
  end
end
```

2021-04-29 13:51 UTC, mktakuya commented on app/controllers/results_controller.rb
> +      @place_id = place.id
`ZeroDivisionError` が出てしまう箇所、つまりゼロ除算が発生しうる箇所では、例外処理を挟めば良さそうです。

（適当なコード例）

```ruby
a = 10
b = 0

c = begin
  a / b
rescue => ZeroDivisionError
  0
end
```

2021-04-29 13:51 UTC, mktakuya commented on app/controllers/results_controller.rb
> +      @place_id = place.id
上記対応をすれば、 `place_id` をインスタンス変数にしなくても良さそうですかね

2021-04-29 13:51 UTC, mktakuya commented on db/migrate/20210419060241_remove_place_name_from_results.rb
> +    remove_column :results, :place_name, :text
すみません、「これは Place で持ってるので、消す感じでOKですね！」は、このファイルの内容でOKですという意味でした。
わかりにくくてすみません:pray:

2021-05-02 14:33 UTC, pekorinko commented on app/controllers/results_controller.rb
> +      @place_id = place.id
コメントありがとうございます！
@place_idからplace_idに変更すると`ZeroDivisionError`が出てしまう原因について以下ご指摘頂いた箇所と関連するのですが、`check_credibility.rb`で`attr_reader :place_id`をしていなかったことが原因でした。
`attr_reader :place_id`を記載しなかったがためにinitializeメソッドで定義した@place_idをcredibilityメソッドで読み取ることが出来ずReview・Placeどちらにもplace_idが渡っていなかったようです。

https://github.com/pekorinko/review_check/pull/22#discussion_r624701950

2021-05-09 00:59 UTC, mktakuya requested changes

2021-05-09 00:59 UTC, mktakuya commented on lib/my_tools/check_credibility.rb
> +    attr_reader :place_id
`CheckCredibility` の `place_id` って外部から参照しますかね？

2021-05-09 04:05 UTC, pekorinko commented on lib/my_tools/check_credibility.rb
> +    attr_reader :place_id
ご指摘いただきありがとうございます！こちら外部からの参照無いので`attr_reader :place_id`削除しました！

2021-05-09 20:56 UTC, closed without merging