直近５件のResultをトップページで表示
pekorinko/review_check pull request #31
Opened 2021-04-21 11:20 UTC by pekorinko

## やったこと
- 直近５件のResultをトップページで表示する
- place_idがかぶっているResultは除いて引っ張ってくるようにする(ユニークなレコード)
## やった理由
- トップページが味気なかったため
## 確認項目
-[x]

## Issue
Fix #26

2021-04-29 13:44 UTC, mktakuya commented
@pekorinko Historyクラス新たに作らなくても、そのままResultクラスを使えば良いと思います。Historyクラスの持つ属性（ `star_ave` など）って、Resultクラスと全く一緒だと思うので。

2021-04-29 13:46 UTC, mktakuya requested changes
コード中に1点コメントしました。
また、そもそも `History` クラスは必要なさそうな旨のコメントもしました！

2021-04-29 13:46 UTC, mktakuya commented on app/controllers/results_controller.rb
> +      Result.select('DISTINCT ON (place_id) *').order(place_id: :desc).limit(5)
`select('DISTINCT ON (place_id')` は、 `distinct(:place_id)` で書けますね。
あんまり生SQLを書かないほうが良いです。

```suggestion
      Result.distinct(:place_id).order(place_id: :desc).limit(5)
```

2021-05-02 13:31 UTC, pekorinko commented on app/controllers/results_controller.rb
> +      Result.select('DISTINCT ON (place_id) *').order(place_id: :desc).limit(5)
コメントありがとうございます！
```
Result.distinct(:place_id).order(place_id: :desc).limit(5)
```
でやったところ、place_idが被った状態で検索履歴が表示されてしまい、`distinct(:place_id)`が効いていないようでした。
以下のissueに該当する問題ないのですがなぜ`distinct(:place_id)`が効かないのか調べても原因が分からない状況です。`distinct(:place_id)`が効かなくなる原因ご存知でしたらアドバイスいただけますと幸いです。
https://github.com/pekorinko/review_check/issues/26#issuecomment-824825348


【Result.distinct(:place_id).order(place_id: :desc).limit(5)　の場合】
- **place_idがかぶる**

![image](https://user-images.githubusercontent.com/61894818/116814668-09edfa80-ab95-11eb-8cda-15b94ec00a51.png)


【 Result.select('DISTINCT ON (place_id) *').order(place_id: :desc).limit(5)　の場合】
- **place_idが被らない**

![image](https://user-images.githubusercontent.com/61894818/116814621-d7440200-ab94-11eb-9e2c-5244f80cd1b3.png)

2021-05-04 01:32 UTC, pekorinko commented
コメントありがとうございます！
Historyクラスについてなぜ必要だと考えたのかを自分の中で整理しました。
思考の詳細→https://github.com/pekorinko/review_check/issues/47

結論としてHistoryクラスは必要という考えに至りました。Historyクラスを作った背景として、
- 直近５件の閲覧履歴をトップページで表示したい
- そのためにResultとPlaceの情報を併せ持ったデータをnew.html.erbで表示したい
という考えが根底にあります。

そしてこれを実現させるために、初めはresult_controller.rbのnewメソッドにてResultの直近５件を取得してnew.html.erb でeach処理をして必要項目を表示させる手法を取っていました。またPlaceに関しても同様にビューの中でレコードを呼び出す処理を行っていました。
```
【result_controller.rb】
def new
    @result_histories = Result.last(5)
  end
```
```
【new.html.erb】
<h1>直近の検索結果</h1>
<% @result_histories.each do |result_history| %>
    <% @place_histories = Place.find(result_history.place_id) %>
    <p>店舗名：<%= @place_histories.place_name %></p>
    <p>住所：<%= @place_histories.address %></p>
    <p>平均投稿数：<%= result_history.count_ave %></p>
    <p>平均星評価：<%= result_history.star_ave %></p>
    <p>平均文字数：<%= result_history.text_ave %></p>
<% end %>
<p>＊厳選された星評価＝文字数50文字以上かつ投稿件数20件以上の投稿者に絞った場合の星評価</p>
```

ただ、ビューでレコードを呼び出す処理を行うのはMVC的におかしいということに気づいたため、result_controller.rb上でPlaceとResultの必要情報を組み合わせたインスタンスを作り、これをビューで表示させる手法に変えたほうが良いと考えました。

そこでPlaceとResultの必要情報を組み合わせたHistoryクラスを作り、インスタンス化したものをビューで呼び出すことでMVCにも反しない形で過去の検索履歴を表示出来ると考えました。

上記の理由からHitoryクラスは必要だと考えたのですが、もしMVCに反しない形でビューで表示するための手法があればアドバイス頂けますと幸いです！

2021-05-09 02:24 UTC, mktakuya commented
`@place_histories = Place.find(result_history.place_id)` を view でやるのでなく、↓のように、 `result_history` から直接 `place` を引いてくれば良さそう。

```erb
<h1>直近の検索結果</h1>
<% @result_histories.each do |result_history| %>
    <% @place_histories = Place.find(result_history.place_id) %>
    <p>店舗名：<%= result_history.place.place_name %></p>
    <p>住所：<%= result_history.place.address %></p>
    <p>平均投稿数：<%= result_history.count_ave %></p>
    <p>平均星評価：<%= result_history.star_ave %></p>
    <p>平均文字数：<%= result_history.text_ave %></p>
<% end %>
<p>＊厳選された星評価＝文字数50文字以上かつ投稿件数20件以上の投稿者に絞った場合の星評価</p>
```

2021-05-09 03:50 UTC, merged