Place model
pekorinko/review_check pull request #4
Opened 2021-03-14 01:03 UTC by pekorinko

## やったこと

## やった理由

## 確認項目
-[ ]

## スクリーンショット

2021-03-16 13:00 UTC, mktakuya requested changes
色々コメントしました！

2021-03-16 13:00 UTC, mktakuya commented on lib/my_tools/place_data_scraper.rb
> +      # Place.create!(place_name: 'カオマンガイバザール', address: '東京都三鷹市')
消し忘れ注意です〜

2021-03-16 13:00 UTC, mktakuya commented on test/fixtures/results.yml
> +  url: MyString
これmodel作成時（ `rails g model Result` ）に勝手に作成されるやつですね。
フィクスチャといって、テスト用データを生成してくれるやつです。

今回はResultモデル結局いらなくなったはずなので、ファイルごと消しておきましょうか。

2021-03-16 13:00 UTC, mktakuya commented on lib/my_tools/place_data_scraper.rb
> +        )
これ `!` つけた意図ってありますかね？

2021-03-16 13:00 UTC, mktakuya commented on lib/my_tools/place_data_scraper.rb
> +      Place.create!(place_name: result[:place_name], address: result[:address])
こちらも、 `create` ではなく `create!` を使った意図ってありますか？

2021-03-16 13:00 UTC, mktakuya commented on db/migrate/20210302124316_create_reviews.rb
> +      t.string :text, null: true
出来るだけNULL許可はしないほうが良い（ = NOT NULL制約をつけたほうが良い）です。
string型のカラムで評価なしの場合は、 `nil` ではなく空文字列 `""` をいれるようにすると良いでしょう。

2021-03-17 14:53 UTC, mktakuya requested changes

2021-03-17 14:53 UTC, mktakuya commented on lib/my_tools/selenium_tool.rb
> +    end
`||=` を使うのはナイスです！
でも、惜しいです。
`||=` は、左辺が偽か未定義なら、右辺を左辺に代入する演算子です。

`@content ||= ""` の時点で、「 `@content` が `nil` なら空文字列 `''` を代入する」という意味になっているので、その上段の `if @content == nil` は必要ありません。

2021-03-17 14:53 UTC, mktakuya commented on lib/my_tools/selenium_tool.rb
> +    end
理解するためのヒント:

```ruby
# irb や rails console等で
content = "aaa"
content ||= "uwagaki"
content
#=> "aaa"

content2 = nil
content2 ||= "uwagaki"
content2
#=> "uwagaki"
```

補足:
Rubyのサンプルコード等において、 `#=>` という表現は、返り値を指します。
例えば

```ruby
sum(2, 3)
#=> 5
```

というサンプルコードがあった場合、 `sum(2, 3)` を実行すると `5` が返ってきたという意味になります。

2021-03-17 14:53 UTC, mktakuya commented on lib/my_tools/selenium_tool.rb
> +          replace
上の方で `replace` メソッドの中身について言及してしまいましたが、

これくらいのことならメソッドにせずとも1行にまとめて以下のように書くか、

```
@content = review_item.find_element(:class_name, 'review-full-text') || ''
```

2行に分けて以下のように書いてしまって良いと思います。

```ruby
@content = review_item.find_element(:class_name, 'review-full-text')
@content ||= ''
```

僕なら前者にしますね〜。感覚ですが。

2021-03-18 13:41 UTC, pekorinko reviewed
反映できていなかったコメントを返しました。

2021-03-18 13:41 UTC, pekorinko commented on test/fixtures/results.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
自動で生成されたファイルのようなのですが、使用していないため削除したほうが良いでしょうか？

2021-03-18 13:41 UTC, pekorinko commented on lib/my_tools/place_data_scraper.rb
> +        )
Reviewテーブルへのデータ格納がうまくいかなかった際にデバッグ用で「!」を付けました。こちら問題なく挙動するようになったため本番用では「!」を消したほうが良いでしょうか？

2021-03-18 13:41 UTC, pekorinko commented on lib/my_tools/place_data_scraper.rb
> +      Place.create!(place_name: result[:place_name], address: result[:address])
Placeテーブルへのデータ格納がうまくいかなかった際にデバッグ用で「!」を付けました。こちら問題なく挙動するようになったため本番用では「!」を消したほうが良いでしょうか？

2021-03-18 13:41 UTC, pekorinko commented on db/migrate/20210302124316_create_reviews.rb
> +      t.string :text, null: false
textをNotNull制約にしても動くようにlib/my_tools/selenium_tool.rbにて口コミ本文がnilの際は空文字列を返すようにプログラムを変更しました。

2021-03-18 13:41 UTC, pekorinko commented on lib/my_tools/selenium_tool.rb
> +          if content == nil
db/migrate/20210302124316_create_reviews.rbにてtextをNotNull制約にしたため、口コミ本文がnilの際は空文字列を返すようにプログラムを変更しました。

2021-03-20 02:05 UTC, mktakuya approved these changes
1点コメントしましたがまぁ動いてるので良いと思います。

2021-03-20 02:05 UTC, mktakuya commented on lib/my_tools/place_data_scraper.rb
> +        )
@pekorinko なるほどです〜。
`create` と `create!` の違いはデータ作成失敗時の挙動です。
前者はデータ作成失敗時に `false` を返し、後者は例外を起こします。
例外が起こるとプログラムが終了するので、デバッグ用にはわかりやすいかもしれませんね。

本番のコードでは、上段の `ApplicationController` で例外をキャッチしている場合や、トランザクションなど例外を起こさせたい場合（どちらも今度説明します）以外は `false` 返すようにして、if文でハンドリングすると良いかな、と思っています。

2021-03-21 03:13 UTC, pekorinko commented
ありがとうございます！承知致しました。
今回は「!」を消してデータ作成が失敗したときにfalseを返すように変更しました。
優先度の高い信憑性チェック機能作成が完了次第、falseが出た場合のハンドリング処理にも手を付けたいと思います。

2021-03-21 03:20 UTC, mktakuya approved these changes

2021-03-21 03:20 UTC, mktakuya commented on app/models/review.rb
> +  validates :text, presence: false
この行はわざわざ書かなくても良いです（デフォルトでそうなっているので）

2021-03-21 06:03 UTC, merged